# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
  
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  
branches:
 only:
   - master
   
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
   
codecov: true

notifications:
  email: false
  
env:
  - PYTHON=""

#script:
#  - julia -e 'using Pkg; Pkg.test("ScenTrees",coverage=true)'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); using Documenter; include("docs/make.jl")'
      after_success: skip
       
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ScenTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("ScenTrees")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
